In [ ]:
import tensorflow as tf
import numpy as np 

TF變數類型主要有三種，tf.constant、tf.Variable以及tf.placeholder。

1.tf.constant: 一個constant的類別，你可以放入各式的資料型態，做一些基礎運算，Ex: tf.add 等等。

2.tf.Variable: 放置可學習的變數或者說將可求導的變數，例如: Neural Network的wieght或者bias。

3.tf.placeholder: 在TF2.0中，已經不使用這個變數。

一 ，Tensorflow基本語法

In [ ]:
#使用tf.constant創建[1., 2., 3.]
a = tf.constant([1,2,3],dtype = tf.float32)
a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
#使用tf.range創建[1, 3, 5, 7, 9]
b = tf.range(1,10,delta = 2)
b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [ ]:
#用tf.linspace創建0.,6.,12.,18.,24.的數組
c = tf.linspace(0.0,24.0,5)
c

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0.,  6., 12., 18., 24.], dtype=float32)>

In [ ]:
#用tf.zeros創建[[0., 0., 0.],
#       [0., 0., 0.],
#       [0., 0., 0.]]
d = tf.zeros([3,3])
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
#用tf.zeros_like複製底下的數組
a = tf.ones([3,3])
b = tf.zeros_like(a,dtype= tf.float32)
print(a)
print(b)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
#用tf.fill創建[[5, 5],
#       [5, 5],
#       [5, 5]]
b = tf.fill([3,2],5)
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 5],
       [5, 5],
       [5, 5]], dtype=int32)>

In [ ]:
#用tf.eye創建單位矩陣[[1 0 0]
#          [0 1 0]
#          [0 0 1]]
I = tf.eye(3,3)
tf.print(I)
tf.print(" ")
#用tf.linalg.diag創建對角矩陣[[1 0 0]
#              [0 2 0]
#              [0 0 3]]
t = tf.linalg.diag([1,2,3])
tf.print(t)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
 
[[1 0 0]
 [0 2 0]
 [0 0 3]]


二 ，索引切片

In [ ]:
t = tf.random.uniform([5,5],minval=0,maxval=10,dtype=tf.int32)
t

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[2, 0, 2, 1, 0],
       [7, 7, 9, 6, 6],
       [7, 9, 7, 7, 7],
       [7, 6, 9, 2, 1],
       [3, 7, 0, 4, 0]], dtype=int32)>

In [ ]:
#第0行
t[0]

In [ ]:
#最後一行
t[-1]

In [ ]:
#第1行第3列
tf.print(t[1,3])
tf.print(t[1][3])

In [ ]:
#第1行至第3行
tf.print(t[1:4,:])
tf.print(tf.slice(t,[1,0],[3,5]))

**三，維度變換**

維度變換相關函數主要有tf.reshape, tf.squeeze, tf.expand_dims, tf.transpose.

1.tf.reshape: 可以改變張量的形狀。

2.tf.squeeze: 可以減少維度。

3.tf.expand_dims: 可以增加維度。

4.tf.transpose: 可以交換維度。

In [ ]:
a = tf.random.uniform(shape=[1,3,3,2], minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)
tf.print(a)

In [ ]:
#改成[3,6]形狀的張量
b = tf.reshape(a,[3,6])
tf.print(b.shape)
tf.print(b)

In [ ]:
#改回成[1,3,3,2]形狀的張量
c = tf.reshape(b,[1,3,3,2])
c

In [ ]:
#如果張量在某個維度上只有一個元素，利用tf.squeeze可以消除這個維度。
s = tf.squeeze(a)
tf.print(s.shape)
tf.print(s)

In [ ]:
#在第0維插入長度為1的一個維度
d = tf.expand_dims(s,axis=0)
d

In [ ]:
# Batch,Height,Width,Channel
a = tf.random.uniform(shape=[100,600,600,4],minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)

#用tf.transpose轉換成Channel,Height,Width,Batch
s= tf.transpose(a,perm=[3,1,2,0])
tf.print(s.shape)