Ref: https://www.tensorflow.org/api_docs/python/tf/keras/utils/to_categorical

https://keras.io/zh/losses/

https://blog.csdn.net/moyu123456789/article/details/83444140

In [ ]:
import tensorflow as tf
import numpy as np

a = tf.keras.utils.to_categorical([0, 1, 2, 3], num_classes=4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [ ]:
a = tf.constant(a, shape=[4, 4])
a

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
b = tf.constant([.9, .04, .03, .03,
          .3, .45, .15, .13,
          .04, .01, .94, .05,
          .12, .21, .5, .17],
        shape=[4, 4])

In [ ]:
loss = tf.keras.backend.categorical_crossentropy(a, b)
print(np.around(loss, 5))

[0.10536 0.82807 0.1011  1.77196]


In [ ]:
loss = tf.keras.backend.categorical_crossentropy(a, a)
print(np.around(loss, 5))

[0. 0. 0. 0.]
