參考: https://www.tensorflow.org/api_docs/python/tf/keras/layers

[class Activation: Applies an activation function to an output.](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Activation)

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
layer = tf.keras.layers.Activation('relu')
output = layer([-3.0, -1.0, 0.0, 2.0])
list(output.numpy())

[0.0, 0.0, 0.0, 2.0]

In [3]:
layer = tf.keras.layers.Activation(tf.nn.relu)
output = layer([-3.0, -1.0, 0.0, 2.0])
list(output.numpy())

[0.0, 0.0, 0.0, 2.0]

[class AveragePooling1D: Average pooling for temporal data.](https://www.tensorflow.org/api_docs/python/tf/keras/layers/AveragePooling1D)

In [4]:
x = tf.constant([1., 2., 3., 4., 5.])
x = tf.reshape(x, [1, 5, 1])
x

<tf.Tensor: shape=(1, 5, 1), dtype=float32, numpy=
array([[[1.],
        [2.],
        [3.],
        [4.],
        [5.]]], dtype=float32)>

#valid

4 = (5 - 2 + 1) / 1

(input_shape - pool_size + 1) / strides)

In [19]:
avg_pool_1d = tf.keras.layers.AveragePooling1D(pool_size=2,
   strides=1, padding='valid')
avg_pool_1d(x)

<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[1.5],
        [2.5],
        [3.5],
        [4.5]]], dtype=float32)>

same

5 / 1 = 5

output_shape = input_shape / strides

In [20]:
avg_pool_1d = tf.keras.layers.AveragePooling1D(pool_size=2,
   strides=1, padding='same')
avg_pool_1d(x)

<tf.Tensor: shape=(1, 5, 1), dtype=float32, numpy=
array([[[1.5],
        [2.5],
        [3.5],
        [4.5],
        [5. ]]], dtype=float32)>

[class Dense: Just your regular densely-connected NN layer.](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense
)

In [12]:
# Create a `Sequential` model and add a Dense layer as the first layer.
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(16,)))
model.add(tf.keras.layers.Dense(32, activation='relu'))
# Now the model will take as input arrays of shape (None, 16)
# and output arrays of shape (None, 32).
# Note that after the first layer, you don't need to specify
# the size of the input anymore:
model.add(tf.keras.layers.Dense(32))
model.output_shape

(None, 32)

[class Dropout: Applies Dropout to the input.](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout)

In [14]:
tf.random.set_seed(0)
layer = tf.keras.layers.Dropout(.5, input_shape=(2,))
data = np.arange(10).reshape(5, 2).astype(np.float32)
print(data)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [18]:
outputs = layer(data, training=True)
print(outputs)

tf.Tensor(
[[ 0.  0.]
 [ 4.  0.]
 [ 0.  0.]
 [12. 14.]
 [16.  0.]], shape=(5, 2), dtype=float32)


[class RNN: Base class for recurrent layers.](https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN)

[class LSTM: Long Short-Term Memory layer - Hochreiter 1997.](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM)

In [9]:
inputs = tf.random.normal([32, 10, 8])
lstm = tf.keras.layers.LSTM(4)
output = lstm(inputs)
print(output.shape)

(32, 4)


In [10]:
lstm = tf.keras.layers.LSTM(4, return_sequences=True, return_state=True)
whole_seq_output, final_memory_state, final_carry_state = lstm(inputs)
print(whole_seq_output.shape)
print(final_memory_state.shape)
print(final_carry_state.shape)

(32, 10, 4)
(32, 4)
(32, 4)
